[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
ewebsock = {workspace = true}
common = {path = "../common"}
bincode = { workspace = true }
serde = { workspace = true }
serde_json ={ workspace = true }