[workspace]
resolver = "2"
members = ["server"]

[package]
name = "netcode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {workspace = true}

[workspace.dependencies]
hyper = {version = "1.1", features = ["server", "http1"]}
hyper-tungstenite = "0.13"
tokio = {version = "1.36", features = ["full"]}
serde = {version = "1.0", features = ["derive"]}
bincode = "1.3"
