[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path="../common"}
tokio = {workspace = true}
hyper = {workspace = true}
tokio-util = {workspace = true}

[dev-dependencies]
tokio-test = {workspace = true}